[package]
name = "hardware-check"
version = "0.1.0"
authors = ["Anatol Ulrich <anatol.ulrich@ferrous-systems.com>"]
edition = "2021"
resolver = "2"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = ["native"]
native = ["esp-idf-sys/native"]

[dependencies]
esp-idf-sys = { version = "0.30", features = ["binstart"] }
esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf-svc.git", rev = "a39c119", features = ["experimental", "alloc"] }
esp-idf-hal = "0.32"
embedded-svc = "0.16"
log = "0.4"
anyhow = "1"
toml-cfg = "0.1"
simple_logger = {version = "2.1", features = ["colored"], default-features = false} # TODO: "time" default feature doesn't build unter espc3
riscv = { version = "0.7", features=["inline-asm"] }
bsc = { path = "../../common/lib/bsc" }

[build-dependencies]
embuild = "0.28"
anyhow = "1"
toml = "0.5"
